name: XcraftAnimalProtect
version: 1.1.5
author: INemesisI
description: Requires XcraftLibrary v1.6.0

main: de.xcraft.INemesisI.AnimalProtect.XcraftAnimalProtect
load: POSTWORLD

depend: [XcraftLibrary, WorldGuard]
    
permissions:
    XcraftAnimalProtect:
        children:
            XcraftAnimalProtect.Attack: false
            XcraftAnimalProtect.Interact: false
        default: true